package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private int idSchedule;
	private Subject subject;
	private String dayWeek;
	private String hour;
	private Date dayYear;
	private Integer classroom;

	public Schedule() {
	}

	public Schedule(Subject subject, String dayWeek, String hour, Date dayYear, Integer classroom) {
		this.subject = subject;
		this.dayWeek = dayWeek;
		this.hour = hour;
		this.dayYear = dayYear;
		this.classroom = classroom;
	}

	public int getIdSchedule() {
		return this.idSchedule;
	}

	public void setIdSchedule(int idSchedule) {
		this.idSchedule = idSchedule;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getDayWeek() {
		return this.dayWeek;
	}

	public void setDayWeek(String dayWeek) {
		this.dayWeek = dayWeek;
	}

	public String getHour() {
		return this.hour;
	}

	public void setHour(String hour) {
		this.hour = hour;
	}

	public Date getDayYear() {
		return this.dayYear;
	}

	public void setDayYear(Date dayYear) {
		this.dayYear = dayYear;
	}

	public Integer getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Integer classroom) {
		this.classroom = classroom;
	}

}
