package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private int idSubject;
	private Teacher teacher;
	private String code;
	private Integer hours;
	private Set schedules = new HashSet(0);
	private Set courses = new HashSet(0);

	public Subject() {
	}

	public Subject(Teacher teacher, String code, Integer hours, Set schedules, Set courses) {
		this.teacher = teacher;
		this.code = code;
		this.hours = hours;
		this.schedules = schedules;
		this.courses = courses;
	}

	public int getIdSubject() {
		return this.idSubject;
	}

	public void setIdSubject(int idSubject) {
		this.idSubject = idSubject;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getHours() {
		return this.hours;
	}

	public void setHours(Integer hours) {
		this.hours = hours;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
