package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private int idRegistration;
	private Student student;
	private Course course;
	private String typeRegistration;
	private Boolean onDual;
	private Timestamp dateRegistration;

	public Registration() {
	}

	public Registration(Student student, Course course) {
		this.student = student;
		this.course = course;
	}

	public Registration(Student student, Course course, String typeRegistration, Boolean onDual,
			Timestamp dateRegistration) {
		this.student = student;
		this.course = course;
		this.typeRegistration = typeRegistration;
		this.onDual = onDual;
		this.dateRegistration = dateRegistration;
	}

	public int getIdRegistration() {
		return this.idRegistration;
	}

	public void setIdRegistration(int idRegistration) {
		this.idRegistration = idRegistration;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getTypeRegistration() {
		return this.typeRegistration;
	}

	public void setTypeRegistration(String typeRegistration) {
		this.typeRegistration = typeRegistration;
	}

	public Boolean getOnDual() {
		return this.onDual;
	}

	public void setOnDual(Boolean onDual) {
		this.onDual = onDual;
	}

	public Timestamp getDateRegistration() {
		return this.dateRegistration;
	}

	public void setDateRegistration(Timestamp dateRegistration) {
		this.dateRegistration = dateRegistration;
	}

}
