package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private int idTeacher;
	private Boolean registered;
	private String passwordHashed;
	private Integer passwordNotHashed;
	private String email;
	private String dni;
	private String name;
	private String lastName;
	private String address;
	private String phone1;
	private String phone2;
	private Set subjects = new HashSet(0);
	private Set meetingRequestsForIdHost = new HashSet(0);
	private Set meetingRequestsForIdGuest = new HashSet(0);

	public Teacher() {
		
	}

	public Teacher(Boolean registered, String passwordHashed, Integer passwordNotHashed, String email, String dni,
			String name, String lastName, String address, String phone1, String phone2, Set subjects,
			Set meetingRequestsForIdHost, Set meetingRequestsForIdGuest) {
		this.registered = registered;
		this.passwordHashed = passwordHashed;
		this.passwordNotHashed = passwordNotHashed;
		this.email = email;
		this.dni = dni;
		this.name = name;
		this.lastName = lastName;
		this.address = address;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.subjects = subjects;
		this.meetingRequestsForIdHost = meetingRequestsForIdHost;
		this.meetingRequestsForIdGuest = meetingRequestsForIdGuest;
		
	}

	public int getIdTeacher() {
		return this.idTeacher;
	}

	public void setIdTeacher(int idTeacher) {
		this.idTeacher = idTeacher;
	}

	public Boolean getRegistered() {
		return this.registered;
	}

	public void setRegistered(Boolean registered) {
		this.registered = registered;
	}

	public String getPasswordHashed() {
		return this.passwordHashed;
	}

	public void setPasswordHashed(String passwordHashed) {
		this.passwordHashed = passwordHashed;
	}

	public Integer getPasswordNotHashed() {
		return this.passwordNotHashed;
	}

	public void setPasswordNotHashed(Integer passwordNotHashed) {
		this.passwordNotHashed = passwordNotHashed;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public Set getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set subjects) {
		this.subjects = subjects;
	}

	public Set getMeetingRequestsForIdHost() {
		return this.meetingRequestsForIdHost;
	}

	public void setMeetingRequestsForIdHost(Set meetingRequestsForIdHost) {
		this.meetingRequestsForIdHost = meetingRequestsForIdHost;
	}

	public Set getMeetingRequestsForIdGuest() {
		return this.meetingRequestsForIdGuest;
	}

	public void setMeetingRequestsForIdGuest(Set meetingRequestsForIdGuest) {
		this.meetingRequestsForIdGuest = meetingRequestsForIdGuest;
	}

}
