package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int idCourse;
	private String name;
	private Set registrations = new HashSet(0);
	private Set subjects = new HashSet(0);

	public Course() {
	}

	public Course(int idCourse) {
		this.idCourse = idCourse;
	}

	public Course(int idCourse, String name, Set registrations, Set subjects) {
		this.idCourse = idCourse;
		this.name = name;
		this.registrations = registrations;
		this.subjects = subjects;
	}

	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set registrations) {
		this.registrations = registrations;
	}

	public Set getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set subjects) {
		this.subjects = subjects;
	}

}
