package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Meeting generated by hbm2java
 */
public class Meeting implements java.io.Serializable {

	private int idMeeting;
	private String dayWeek;
	private String hour;
	private Date dayYear;
	private Integer classroom;
	private String receiver;
	private Boolean confirmed;
	private String title;
	private Integer numGuests;
	private Integer remainingAcceptance;
	private String topic;
	private Set meetingRequests = new HashSet(0);

	public Meeting() {
	}

	public Meeting(String dayWeek, String hour, Date dayYear, Integer classroom, String receiver, Boolean confirmed,
			String title, Integer numGuests, Integer remainingAcceptance, String topic, Set meetingRequests) {
		this.dayWeek = dayWeek;
		this.hour = hour;
		this.dayYear = dayYear;
		this.classroom = classroom;
		this.receiver = receiver;
		this.confirmed = confirmed;
		this.title = title;
		this.numGuests = numGuests;
		this.remainingAcceptance = remainingAcceptance;
		this.topic = topic;
		this.meetingRequests = meetingRequests;
	}

	public int getIdMeeting() {
		return this.idMeeting;
	}

	public void setIdMeeting(int idMeeting) {
		this.idMeeting = idMeeting;
	}

	public String getDayWeek() {
		return this.dayWeek;
	}

	public void setDayWeek(String dayWeek) {
		this.dayWeek = dayWeek;
	}

	public String getHour() {
		return this.hour;
	}

	public void setHour(String hour) {
		this.hour = hour;
	}

	public Date getDayYear() {
		return this.dayYear;
	}

	public void setDayYear(Date dayYear) {
		this.dayYear = dayYear;
	}

	public Integer getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Integer classroom) {
		this.classroom = classroom;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public Boolean getConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(Boolean confirmed) {
		this.confirmed = confirmed;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getNumGuests() {
		return this.numGuests;
	}

	public void setNumGuests(Integer numGuests) {
		this.numGuests = numGuests;
	}

	public Integer getRemainingAcceptance() {
		return this.remainingAcceptance;
	}

	public void setRemainingAcceptance(Integer remainingAcceptance) {
		this.remainingAcceptance = remainingAcceptance;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Set getMeetingRequests() {
		return this.meetingRequests;
	}

	public void setMeetingRequests(Set meetingRequests) {
		this.meetingRequests = meetingRequests;
	}

}
