package DBEntities;
// Generated Jan 23, 2025, 8:11:36 PM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int idStudent;
	private Boolean registered;
	private String email;
	private String passwordHashed;
	private Integer passwordNotHashed;
	private String dni;
	private String name;
	private String lastName;
	private String address;
	private String phone1;
	private String phone2;
	private byte[] foto;
	private Set registrations = new HashSet(0);

	public Student() {
	}

	public Student(Boolean registered, String email, String passwordHashed, Integer passwordNotHashed, String dni,
			String name, String lastName, String address, String phone1, String phone2, byte[] foto,
			Set registrations) {
		this.registered = registered;
		this.email = email;
		this.passwordHashed = passwordHashed;
		this.passwordNotHashed = passwordNotHashed;
		this.dni = dni;
		this.name = name;
		this.lastName = lastName;
		this.address = address;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.foto = foto;
		this.registrations = registrations;
	}

	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

	public Boolean getRegistered() {
		return this.registered;
	}

	public void setRegistered(Boolean registered) {
		this.registered = registered;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswordHashed() {
		return this.passwordHashed;
	}

	public void setPasswordHashed(String passwordHashed) {
		this.passwordHashed = passwordHashed;
	}

	public Integer getPasswordNotHashed() {
		return this.passwordNotHashed;
	}

	public void setPasswordNotHashed(Integer passwordNotHashed) {
		this.passwordNotHashed = passwordNotHashed;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public Set getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set registrations) {
		this.registrations = registrations;
	}

}
